config/routes.rb
Blog::Application.routes.draw do
  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, :only => [:create, :destroy]
  resources :posts, :only => [:create, :destroy]

  root :to => "home#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  self.per_page = 5

  attr_accessible :content

  belongs_to :user

  validates :user_id, :presence => true
  validates :content, :presence => true, :length => { :maximum => 120 }

  default_scope :order => 'created_at DESC'

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id#=integer, :follower_id

  belongs_to :follower, :class_name => "User"
  belongs_to :followed, :class_name => "User"

  validates :follower_id, :presence => true
  validates :followed_id, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :active, :created, :email, :password, :password_confirmation, :username, :remember_me

  # Following & Followers
  has_many :relationships, :foreign_key => "follower_id", :dependent => :destroy
  has_many :followed_users, :through => :relationships, :source => :followed
  has_many :reverse_relationships, :foreign_key => "followed_id", :class_name => "Relationship", :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower

  has_many :posts, :dependent => :destroy
  
  
  # Validations
  validates_confirmation_of :password
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 5..25 }
  validates :email, :presence => true, :uniqueness => true, :length => { :in => 10..30 }, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  #attr_accessible :active, :created, :email, :password, :password_confirmation, :username
  attr_accessor :password_confirmation

  before_save :default_values
  def default_values
    self.active ||= true
    self.created ||= DateTime.now
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(:followed_id => other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  def feed
    Post.from_users_followed_by(self)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # After sign in redirect to user profile page
  def after_sign_in_path_for(user)
        user_url(user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = []
    if user_signed_in?
      @post = current_user.posts.build
      @posts = Post.from_users_followed_by(current_user).paginate(:page => params[:page])
      @following = current_user.followed_users.paginate(:page => params[:followed_page], :per_page => 5)
      @followers = current_user.followers.paginate(:page => params[:follower_page], :per_page => 5)
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :can_delete_post, :only => :destroy

  def create
    @post = current_user.posts.build(params[:post])
    @abc = params[:hello]
    respond_to do |format|
      if @post.save
        format.js {@abc}
      #else
      #  format.js { render :partial => 'error' }
      end
      @posts = current_user.posts.paginate(:page => params[:page])

    end


  end

  def destroy
    @post.destroy
    redirect_to current_user
  end

  private

  def can_delete_post
    @post = current_user.posts.find_by_id(params[:id])
    redirect_to root_path if @post.nil?
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_filter :authenticate_user!

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

#Mail catcher
#Simple rcov

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #http_basic_authenticate_with :name => "dhh", :password => "secret", :except => [:new]
  before_filter :authenticate_user!

  def index
    #@users = User.all
    user_signed_in?
    
    @users = User.paginate(:page => params[:page], :per_page => 10)

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    
    if @user.save
        flash[:notice] = "You Signed up successfully"
        flash[:color]= "valid"
        redirect_to :action => "new"
    else
        flash[:notice] = "Form is invalid"
        flash[:color]= "invalid"
        render :action => "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @post = @user.posts.build
    @posts = @user.posts.paginate(:page => params[:page])

    @default_post_text=''
    if current_user!=@user
      @default_post_text= "@" + @user.username
    end

    respond_to do |format|
    	format.html  # show.html.erb
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(:page => params[:page], :per_page => 5)
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page], :per_page => 5)
    render 'show_follow'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_current_user_all_posts.html.erb
<h3>Posts (<%= @posts.count %>)</h3>
<ol class="current_user_posts">
  <% @posts.each do |post| %>
      <li>
        <%= image_tag("default_profile.png", :size=>"60x60" ) %>

        <div class="post_details">
          <h3><%= post.user.username %></h3>
          <span class="content">
            <%= truncate(post.content, :length => 35, :omission => '...') %>
          </span>
          <span class="timestamp">
              Created <%= time_ago_in_words(post.created_at) %> ago.
          </span>
          <% if current_user == post.user %>
              <%= link_to "delete", post, :method => :delete,
                          :confirm => "You sure?",
                          :title => post.content %>
          <% end %>
        </div>
      </li>
  <% end%>
</ol>

<%= will_paginate @posts %>

app/views/home/index.html.erb
<div class="home">
  <h1>Twitter Test Project</h1>
  <% if user_signed_in? %>
    <% if @posts.any? %>

      <div class="home_post_box">
        <%= render :partial =>  '/posts/post_form', :locals => {:hidden_value => false, :submit_class => "post_sumbit" } %>
      </div>

      <div class="posts_box">
        <%= render "current_user_all_posts", :collection => @posts %>
      </div>

      <div class="relations">

        <div class="following">
          <h2> Following(<%= @following.count %>) </h2>
          <ul class="users">
            <% @following.each do |u| %>
                <li>
                  <%= image_tag("default_profile.png", :size=>"30x30" ) %>
                  <%= link_to u.username, u %>
                </li>
            <% end %>
          </ul>
          <%= will_paginate @following, :param_name => 'followed_page' %>
        </div>
        <div class="followers">
          <h2> Followers(<%= @followers.count %>) </h2>
          <ul class="users">
            <% @followers.each do |u| %>
                <li>
                  <%= image_tag("default_profile.png", :size=>"30x30" ) %>
                  <%= link_to u.username, u %>
                </li>
            <% end %>
          </ul>
          <%= will_paginate @followers, :param_name => 'follower_page' %>
        </div>
      </div>

    <% end %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">


</footer>

app/views/layouts/_header.html.erb
<header class="header">


  <nav id="user_nav" class="nav box">
    <h1 class="logo" > <%= link_to "Rails Tweet",  root_path %></h1>

    <div class="links">
    <% if user_signed_in? %>
        <%= link_to "My profile", current_user %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
    <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="blog">

    <%= render "/layouts/header" %>

    <div class="container">
      <div class="box">

        <%= yield %>

        <!--
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        -->
      </div>
    </div>

    <%= render "/layouts/footer" %>
</body>
</html>

app/views/posts/_post.html.erb
<li>
  <span class="content">
    <%= truncate(post.content, :length => 75, :omission => '...') %>
  </span>
  <span class="timestamp">
    Created <%= time_ago_in_words(post.created_at) %> ago.
  </span>
  <% if current_user == post.user %>
      <%= link_to "delete", post, :method => :delete,
          :confirm => "You sure?",
          :title => post.content %>
  <% end %>
</li>

app/views/posts/_post_form.html.erb
<%= form_for @post, :remote=>true  do |f| %>
    <div class="field">
      <%= f.text_area :content, :placeholder => "Compose new post...", :value => @default_post_text %>
      <%= hidden_field_tag "hello", hidden_value %>
    </div>
    <%= f.submit "Post", :class => submit_class %>  </br>
<% end %>

app/views/posts/_post_js.html.erb
<li>
  <span class="content"><%= @post.content %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(@post.created_at) %> ago.
  </span>
  <% if current_user == @post.user %>
      <%= link_to "delete", @post, :method => :delete,
          :confirm => "You sure?",
          :title => @post.content %>
  <% end %>
</li>

app/views/posts/_post_list.html.erb
<h3>Posts (<%= @posts.count %>)</h3>
<ol class="posts" id="posts_list">
  <%= render @posts %>

</ol>

<%= will_paginate @posts %>

app/views/posts/create.js.erb
if("<%=@abc%>" == "true"){
    $('#posts_list').html("<%= escape_javascript(render('/posts/post_list')) %>")
}
else{
    $('.posts_box').html("<%= escape_javascript(render('/home/current_user_all_posts')) %>")
}
$('#post_content').val("")

app/views/relationships/1create.html.erb
<h1> Relation Created </h1>

app/views/relationships/2destroy.html.erb
<h1>Relations Destroyed</h1>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('/users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('/users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(:followed_id => @user.id), :remote => true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user), :html=> { :method => :delete }, :remote => true) do |f| %>
  <%= f.submit "Unfollow", :class => "btn btn-large" %>
<% end %>

app/views/users/create.html.erb
<h2>User Created</h2>

app/views/users/index.html.erb
<div class="all_users">
  <h1>Users List</h1>

  <table>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th></th>
      <th></th>
    </tr>

    <% @users.each do |user| %>
        <tr>
          <td> <%= image_tag("default_profile.png", :size=>"30x30" ) %> <%= link_to user.username, user %></td>
          <td><%= user.email %></td>
        </tr>
    <% end %>
  </table>

  </br>
  <%= will_paginate @users %>



</div>

app/views/users/new.html.erb
<h2>New User:</h2>

<%= form_for @user do |f| %>

  <p> Username:</br> <%= f.text_field :username %> </p>

  <p> Email:</br> <%= f.text_field :email %> </p>

  <p> Password:</br> <%= f.password_field :password%></p>

  <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>

  <%= f.submit "Sign Up" %></br></br>

  <%= notice %></br>

  <% if @user.errors.any? %>
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being created:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>  
 
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/show.html.erb
<div class="user_details">

  <aside>
    <section>
      <%= image_tag("default_profile.png") %>
      <p>
        <b>Username:</b>
        <%= @user.username %>
      </p>

      <p>
        <b>Email:</b>
        <%= @user.email %>
      </p>

    </section>

    <section>
      <%= render '/users/shared/stats' %>
    </section>

    <section>
      <%= render :partial =>  '/posts/post_form', :locals => {:hidden_value => true, :submit_class => "btn-primary"} %>
    </section>
  </aside>

    <div class="span1">
      <div class="follow_btn_link">
        <%= render 'follow_form' if not current_user==(@user) %>
        <%= link_to 'All users', users_path %>
      </div>

      <% if @user.posts.any? %>
          <div id="posts_list">
            <%= render "/posts/post_list", :collection => @posts %>
          </div>

      <% end %>
    </div>

</div>

app/views/users/show_follow.html.erb
<%= provide(:title, @title) %>
<div class="user_follow">

    <section>
      <h1><%= @user.username %></h1>
      <%#= link_to "My profile", @user %>
    </section>

    <section>
      <%= render '/users/shared/stats' %>
    </section>

     <div class="follow_list">
        <h3><%= @title %></h3>
        <% if @users.any? %>
          <ul class="users">
            <% @users.each do |u| %>
                <li>
                  <%= image_tag("default_profile.png", :size=>"30x30" ) %>
                  <%= link_to u.username, u %>
                </li>
            <% end %>
          </ul>
          <%= will_paginate @users %>

       <% else %>
           <p>Do not have any <%= @title %></p>
       <% end %>


     </div>
</div>